blog/urls.py
from django.urls import path
from .views import Bloglistview, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView


app_name="blog"

urlpatterns = [
    path('inicio/',Bloglistview.as_view(), name="home"),
    path('create/', BlogCreateView.as_view(), name="create"),
    path('<int:pk>/', BlogDetailView.as_view(), name="detail"),
    path('<int:pk>/update/', BlogUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name="delete")

]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import homeview 

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', homeview.as_view(), name="home"),

    path('blog/', include('blog.urls', namespace='blog'))
]

blog/models.py
from django.db import models


# Create your models here.
class post(models.Model):
    title=models.CharField(max_length=250)
    content=models.TextField()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from .models import post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model=post
        fields=('title','content')

blog/views.py
from struct import pack, pack_into
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import View, UpdateView, DeleteView
from .forms import PostCreateForm
from .models import post
from django.urls import reverse_lazy
# Create your views here.
class Bloglistview(View):
    def get(self, request, *args, **kwargs):
        posts = post.objects.all()
        context={
            'posts':posts
            
        }
        return render(request, 'blog_list.html', context)

class BlogCreateView(View):
    def get(self, request, *args, **kwargs):
        form=PostCreateForm()
        context={
            'form':form
        }
        return render(request, 'blog_create.html', context)

    def post(self, request, *args, **kwargs):
         if request.method=="POST":
            form = PostCreateForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data.get('title')
                content = form.cleaned_data.get('content')

                p, created = post.objects.get_or_create(title=title, content=content)
                p.save()
                return redirect('blog:home')

         context={

         }
         return render(request, 'blog_create.html', context)
         
class BlogDetailView(View):
    def get(self, request, pk,*args, **kwargs):
        Post = get_object_or_404 (post, pk=pk)
        context={
            'post':post
        }
        return render(request, 'blog_detail.html', context)


class BlogUpdateView(UpdateView):
    model=post
    fields=['title','content']
    template_name='blog_update.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('blog:detail', kwargs={'pk':pk})



class BlogDeleteView(DeleteView):
    model=post
    template_name='blog_delete.html'
    success_url= reverse_lazy('blog:home')

core/views.py
from django.views.generic import View
from django.shortcuts import render, redirect

class homeview(View):
    def get(self, request, *args, **kwargs):
        context={
            
        }
        return render(request, 'index.html',context)

templates/base.html
{% load tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load tailwind_tags %}
    <title>Document</title>
  
</head>
<body>
    

    {% block content %}{% endblock content %}


</body>
</html>

templates/blog_create.html
<form method="POST">
    {% csrf_token %}
title{{form.title}}
<br>
content{{form.content}}
<button type="submit">submit</button>
</form>

templates/blog_delete.html
are you sure?
<form method="POST">
    {% csrf_token %}
{{form}}
<button type="submit">Delete</button>
</form>

templates/blog_detail.html
{{post.title}}
<br>
{{post.content}}

templates/blog_list.html
{% extends 'base.html' %}
{% block content %}
blog list 
<br>
{%for post in posts%}
<a href="{% url 'blog:detail' post.id %}">{{post.title}}</a>
<a href="{% url 'blog:update' post.id %}">Update</a>
<a href="{% url 'blog:delete' post.id %}">Delete</a>

{%endfor%}
<br>
<a class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" href="{% url 'blog:create' %}">Create</a>

<br>


{% endblock content %}

templates/blog_update.html
<form method="POST">
    {% csrf_token %}
title{{form.title}}
<br>
content{{form.content}}
<button type="submit">update</button>
</form>

templates/index.html
{% extends 'base.html' %}

{% block content %}hola, visita mi <a class="text-blue-500" href="{% url 'blog:home' %}"> blog aqqui</a>{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-grey-lightest font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>